/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PosDineinRouteImport } from './routes/pos-dinein'
import { Route as PosRouteImport } from './routes/pos'
import { Route as NightAuditRouteImport } from './routes/night-audit'
import { Route as MenuManagementRouteImport } from './routes/menu-management'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImpersonateRouteImport } from './routes/impersonate'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ChannelManagerRouteImport } from './routes/channel-manager'
import { Route as BookingEngineRouteImport } from './routes/booking-engine'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'
import { Route as GuestsIdRouteImport } from './routes/guests.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PosDineinRoute = PosDineinRouteImport.update({
  id: '/pos-dinein',
  path: '/pos-dinein',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const NightAuditRoute = NightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuManagementRoute = MenuManagementRouteImport.update({
  id: '/menu-management',
  path: '/menu-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateRoute = ImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelManagerRoute = ChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingEngineRoute = BookingEngineRouteImport.update({
  id: '/booking-engine',
  path: '/booking-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReservationsRoute,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReservationsRoute,
} as any)
const GuestsIdRoute = GuestsIdRouteImport.update({
  id: '/guests/$id',
  path: '/guests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/crm': typeof CrmRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/impersonate': typeof ImpersonateRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/master': typeof MasterRoute
  '/menu-management': typeof MenuManagementRoute
  '/night-audit': typeof NightAuditRoute
  '/pos': typeof PosRoute
  '/pos-dinein': typeof PosDineinRoute
  '/procurement': typeof ProcurementRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/restaurant': typeof RestaurantRoute
  '/revenue': typeof RevenueRoute
  '/rooms': typeof RoomsRoute
  '/setup': typeof SetupRoute
  '/superadmin': typeof SuperadminRoute
  '/users': typeof UsersRoute
  '/guests/$id': typeof GuestsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/crm': typeof CrmRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/impersonate': typeof ImpersonateRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/master': typeof MasterRoute
  '/menu-management': typeof MenuManagementRoute
  '/night-audit': typeof NightAuditRoute
  '/pos': typeof PosRoute
  '/pos-dinein': typeof PosDineinRoute
  '/procurement': typeof ProcurementRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/restaurant': typeof RestaurantRoute
  '/revenue': typeof RevenueRoute
  '/rooms': typeof RoomsRoute
  '/setup': typeof SetupRoute
  '/superadmin': typeof SuperadminRoute
  '/users': typeof UsersRoute
  '/guests/$id': typeof GuestsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/crm': typeof CrmRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/impersonate': typeof ImpersonateRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/master': typeof MasterRoute
  '/menu-management': typeof MenuManagementRoute
  '/night-audit': typeof NightAuditRoute
  '/pos': typeof PosRoute
  '/pos-dinein': typeof PosDineinRoute
  '/procurement': typeof ProcurementRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/restaurant': typeof RestaurantRoute
  '/revenue': typeof RevenueRoute
  '/rooms': typeof RoomsRoute
  '/setup': typeof SetupRoute
  '/superadmin': typeof SuperadminRoute
  '/users': typeof UsersRoute
  '/guests/$id': typeof GuestsIdRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/admin'
    | '/billing'
    | '/booking-engine'
    | '/channel-manager'
    | '/crm'
    | '/front-desk'
    | '/housekeeping'
    | '/impersonate'
    | '/inventory'
    | '/login'
    | '/maintenance'
    | '/master'
    | '/menu-management'
    | '/night-audit'
    | '/pos'
    | '/pos-dinein'
    | '/procurement'
    | '/properties'
    | '/reports'
    | '/reservations'
    | '/restaurant'
    | '/revenue'
    | '/rooms'
    | '/setup'
    | '/superadmin'
    | '/users'
    | '/guests/$id'
    | '/reservations/$id'
    | '/reservations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/admin'
    | '/billing'
    | '/booking-engine'
    | '/channel-manager'
    | '/crm'
    | '/front-desk'
    | '/housekeeping'
    | '/impersonate'
    | '/inventory'
    | '/login'
    | '/maintenance'
    | '/master'
    | '/menu-management'
    | '/night-audit'
    | '/pos'
    | '/pos-dinein'
    | '/procurement'
    | '/properties'
    | '/reports'
    | '/reservations'
    | '/restaurant'
    | '/revenue'
    | '/rooms'
    | '/setup'
    | '/superadmin'
    | '/users'
    | '/guests/$id'
    | '/reservations/$id'
    | '/reservations/new'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/admin'
    | '/billing'
    | '/booking-engine'
    | '/channel-manager'
    | '/crm'
    | '/front-desk'
    | '/housekeeping'
    | '/impersonate'
    | '/inventory'
    | '/login'
    | '/maintenance'
    | '/master'
    | '/menu-management'
    | '/night-audit'
    | '/pos'
    | '/pos-dinein'
    | '/procurement'
    | '/properties'
    | '/reports'
    | '/reservations'
    | '/restaurant'
    | '/revenue'
    | '/rooms'
    | '/setup'
    | '/superadmin'
    | '/users'
    | '/guests/$id'
    | '/reservations/$id'
    | '/reservations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  BookingEngineRoute: typeof BookingEngineRoute
  ChannelManagerRoute: typeof ChannelManagerRoute
  CrmRoute: typeof CrmRoute
  FrontDeskRoute: typeof FrontDeskRoute
  HousekeepingRoute: typeof HousekeepingRoute
  ImpersonateRoute: typeof ImpersonateRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MasterRoute: typeof MasterRoute
  MenuManagementRoute: typeof MenuManagementRoute
  NightAuditRoute: typeof NightAuditRoute
  PosRoute: typeof PosRoute
  PosDineinRoute: typeof PosDineinRoute
  ProcurementRoute: typeof ProcurementRoute
  PropertiesRoute: typeof PropertiesRoute
  ReportsRoute: typeof ReportsRoute
  ReservationsRoute: typeof ReservationsRouteWithChildren
  RestaurantRoute: typeof RestaurantRoute
  RevenueRoute: typeof RevenueRoute
  RoomsRoute: typeof RoomsRoute
  SetupRoute: typeof SetupRoute
  SuperadminRoute: typeof SuperadminRoute
  UsersRoute: typeof UsersRoute
  GuestsIdRoute: typeof GuestsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-dinein': {
      id: '/pos-dinein'
      path: '/pos-dinein'
      fullPath: '/pos-dinein'
      preLoaderRoute: typeof PosDineinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-audit': {
      id: '/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof NightAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-management': {
      id: '/menu-management'
      path: '/menu-management'
      fullPath: '/menu-management'
      preLoaderRoute: typeof MenuManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-manager': {
      id: '/channel-manager'
      path: '/channel-manager'
      fullPath: '/channel-manager'
      preLoaderRoute: typeof ChannelManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-engine': {
      id: '/booking-engine'
      path: '/booking-engine'
      fullPath: '/booking-engine'
      preLoaderRoute: typeof BookingEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/guests/$id': {
      id: '/guests/$id'
      path: '/guests/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof GuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservationsRouteChildren {
  ReservationsIdRoute: typeof ReservationsIdRoute
  ReservationsNewRoute: typeof ReservationsNewRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsIdRoute: ReservationsIdRoute,
  ReservationsNewRoute: ReservationsNewRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  BookingEngineRoute: BookingEngineRoute,
  ChannelManagerRoute: ChannelManagerRoute,
  CrmRoute: CrmRoute,
  FrontDeskRoute: FrontDeskRoute,
  HousekeepingRoute: HousekeepingRoute,
  ImpersonateRoute: ImpersonateRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MasterRoute: MasterRoute,
  MenuManagementRoute: MenuManagementRoute,
  NightAuditRoute: NightAuditRoute,
  PosRoute: PosRoute,
  PosDineinRoute: PosDineinRoute,
  ProcurementRoute: ProcurementRoute,
  PropertiesRoute: PropertiesRoute,
  ReportsRoute: ReportsRoute,
  ReservationsRoute: ReservationsRouteWithChildren,
  RestaurantRoute: RestaurantRoute,
  RevenueRoute: RevenueRoute,
  RoomsRoute: RoomsRoute,
  SetupRoute: SetupRoute,
  SuperadminRoute: SuperadminRoute,
  UsersRoute: UsersRoute,
  GuestsIdRoute: GuestsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
